# Generated by Django 4.0.6 on 2022-09-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0002_profile_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('سفر', 'سفر'), ('سرگرمی', 'سرگرمی'), ('تکنولوژی', 'تکنولوژی'), ('محیط زیست', 'محیط زیست'), ('زیبایی و پوشاک', 'زیبایی و پوشاک'), ('سلامتی', 'سلامتی')], max_length=200),
        ),
        migrations.CreateModel(
            name='Fllowings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
